services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./sigaa_api:/app/sigaa_api # monta o código fonte
    command: uvicorn sigaa_api.main:app --host 0.0.0.0 --port 8080 --reload
